<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'title' => 'required|string',
            'content' => 'required|string',
            'preview_image' => 'file',
            'main_image' => 'file',
            'category_id' => 'required|integer|exists:categories,id',
            'tag_ids' => 'nullable|array',
            'tag_ids.*' => 'nullable|integer|exists:tags,id'
        ];
    }
    public function messages()
    {
        return ['title.required' => 'Это поле необходимо заполнить',
            'title.string' => 'Данные должны быть строчного типа',
            'content.required' => 'Это поле необходимо заполнить',
            'content.string' => 'Данные должны быть строчного типа',

            'preview_image.file' => 'Выберите файл',

            'main_image.file' => 'Выберите файл',
            'category_id.required' => 'Это поле необходимо заполнить',
            'category_id.exists:categories,id' => 'Некорректная категория',
//            'tag_ids.*.exists:categories,id' => 'Некорректный тег'

        ]; // TODO: Change the autogenerated stub
    }
}
